language: minimal

git:
  depth: 3

before_install:
    - ./checkout-sdk.sh

script:
    - cd docker
    - echo MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD >> .env
    - echo JOOMLA_ADMIN_PASSWORD=$JOOMLA_ADMIN_PASSWORD >> .env
    - ./run-tests.sh
