version: '3.1'

services:
  joomla:
    build:
      context: ./docker/
      args:
        BRANCH: "master"
    restart: always
    links:
      - joomladb:mysql
    ports:
      - "6001:443"
    environment:
      JOOMLA_DB_NAME: yotijoomla
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: root

  joomladb:
    image: mysql:latest
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
