version: '3.1'

services:
  joomla-base:
    depends_on:
      - joomladb
    build:
      context: ./
      dockerfile: app.base.dockerfile

  joomla:
    depends_on:
      - joomladb
      - joomla-base
    build:
      context: ./
      dockerfile: app.dockerfile
      args:
        BRANCH: "master"
    restart: always
    links:
      - joomladb:mysql
    ports:
      - "6001:443"
    environment:
      JOOMLA_DB_NAME: yotijoomla
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: root

  joomladb:
    image: mysql:5.6
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
