version: '3.1'

services:
  joomla-base:
    build:
      context: ./
      dockerfile: app.base.dockerfile
    environment: &joomla-env
      JOOMLA_DB_NAME: yotijoomla
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: root
    depends_on:
      - joomladb
    restart: always
    ports:
      - "6003:443"

  joomla:
    depends_on:
      - joomladb
    build:
      context: ./
      dockerfile: app.dockerfile
      args:
        BRANCH: "master"
    restart: always
    ports:
      - "6001:443"
    environment:
      <<: *joomla-env

  joomla-dev:
    depends_on:
      - joomladb
    build: &dev-build
      context: ../
      dockerfile: docker/app.dev.dockerfile
    restart: always
    ports:
      - "6002:443"
    environment:
      <<: *joomla-env
    volumes:
      - ../yoti/com_yoti.xml:/var/www/html/administrator/components/com_yoti/com_yoti.xml
      - ../yoti/admin:/var/www/html/administrator/components/com_yoti
      - ../yoti/site:/var/www/html/components/com_yoti
      - ../yoti/modules/mod_yoti:/var/www/html/modules/mod_yoti
      - ../yoti/plugins/yotiprofile:/var/www/html/plugins/user/yotiprofile

  joomla-test:
    depends_on:
      - joomladb
      - selenium-node
    build:
      <<: *dev-build
    restart: always
    ports:
      - "6004:443"
    environment:
      <<: *joomla-env
    volumes:
      - ../yoti/:/var/www/html/yoti-joomla
      - ../codeception.yml:/var/www/html/codeception.yml
      - ../tests/:/var/www/html/tests/

  joomladb:
    image: mysql:5.6
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  selenium:
    image: selenium/hub:3.141.59-krypton
    container_name: selenium-hubdocker
    ports:
      - "4444:4444"

  selenium-node:
    image: selenium/node-chrome:3.141.59-krypton
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444
