version: '3.1'

services:
  joomla-base:
    depends_on:
      - joomladb
    build:
      context: ./
      dockerfile: app.base.dockerfile

  joomla:
    depends_on:
      - joomladb
      - joomla-base
    build:
      context: ./
      dockerfile: app.dockerfile
      args:
        BRANCH: "master"
    restart: always
    links:
      - joomladb:mysql
    ports:
      - "6001:443"
    environment:
      JOOMLA_DB_NAME: yotijoomla
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: root

  joomla-dev:
    depends_on:
      - joomladb
      - joomla-base
    build:
      context: ../
      dockerfile: docker/app.dev.dockerfile
    restart: always
    links:
      - joomladb:mysql
    ports:
      - "6002:443"
    environment:
      JOOMLA_DB_NAME: yotijoomla
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: root
    volumes:
      - ../yoti/com_yoti.xml:/var/www/html/administrator/components/com_yoti/com_yoti.xml
      - ../yoti/admin:/var/www/html/administrator/components/com_yoti
      - ../yoti/site:/var/www/html/components/com_yoti
      - ../yoti/modules/mod_yoti:/var/www/html/modules/mod_yoti
      - ../yoti/plugins/yotiprofile:/var/www/html/plugins/user/yotiprofile

  joomladb:
    image: mysql:5.6
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
